AdPackSimMvc/Models/ErrorViewModel.cs
using System;

namespace AdPackSimMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AdPackSimMvc/Controllers/GenericListController.cs
using AdPackSimLib;
using AdPackSimLib.Calculators;
using AdPackSimMvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AdPackSimMvc.Controllers
{
    public class GenericListController : Controller
    {
        private readonly IGenericList _genericList;

        public GenericListController(IGenericList genericList) =>
            _genericList = genericList;

        public IActionResult Index() =>
            View(Data.Default);

        [HttpPost]
        public IActionResult Calculate([FromForm] Data input) =>
            View("Index", _genericList.Calculate(input));

        [HttpPost]
        public IActionResult OptimalTotalDays([FromForm] Data input) =>
            View("Index", _genericList.OptimalTotalDays(input));

        [HttpPost]
        public IActionResult OptimalReinvestingDays([FromForm] Data input) =>
            View("Index", _genericList.OptimalReinvestingDays(input));

        [HttpPost]
        public IActionResult OptimalInitialPacks([FromForm] Data input) =>
            View("Index", _genericList.OptimalInitialPacks(input));

        [HttpPost]
        public IActionResult ToROL([FromForm] Data input) =>
            View("Index", _genericList.ToROL(input));

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() =>
            View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

AdPackSimMvc/Controllers/HomeController.cs
using AdPackSimMvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace AdPackSimMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AdPackSimMvc/Controllers/UnsafeStructArrayController.cs
using AdPackSimLib;
using AdPackSimLib.Calculators;
using AdPackSimMvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AdPackSimMvc.Controllers
{
    public class UnsafeStructArrayController : Controller
    {
        private readonly IUnsafeStructArray _unsafeStructArray;

        public UnsafeStructArrayController(IUnsafeStructArray unsafeStructArray) =>
            _unsafeStructArray = unsafeStructArray;

        public IActionResult Index() =>
            View(Data.Default);

        [HttpPost]
        public IActionResult Calculate([FromForm] Data input) =>
            View("Index", _unsafeStructArray.Calculate(input));

        [HttpPost]
        public IActionResult OptimalTotalDays([FromForm] Data input) =>
            View("Index", _unsafeStructArray.OptimalTotalDays(input));

        [HttpPost]
        public IActionResult OptimalReinvestingDays([FromForm] Data input) =>
            View("Index", _unsafeStructArray.OptimalReinvestingDays(input));

        [HttpPost]
        public IActionResult OptimalInitialPacks([FromForm] Data input) =>
            View("Index", _unsafeStructArray.OptimalInitialPacks(input));

        [HttpPost]
        public IActionResult ToROL([FromForm] Data input) =>
            View("Index", _unsafeStructArray.ToROL(input));

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() =>
            View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

AdPackSimMvc/Views/GenericList/Index.cshtml
@model Data;

<h1>Safe code using a generic List</h1>

<p>Calculate: Safe code using a generic List.</p>

@{ 
    ViewData["Title"] = "Generic List";
    ViewBag.Controller = "GenericList";
    await Html.RenderPartialAsync("Calculator", Model);
}

AdPackSimMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>Welcome to AdPackSimMvc!</h1>

AdPackSimMvc/Views/Shared/Calculator.cshtml
@model Data;

@{ var controller = ViewBag.Controller; }

<form method="post">
    <div>
        <table>
            <tr>
                <td>Total days</td>
                <td>Reinvesting days</td>
                <td>Initial packs</td>
                <td>Return/Day/Pack</td>
                <td>Exchange rate</td>
            </tr>
            <tr>
                <td><input type="number" name="TotalDays" value="@Model.TotalDays" /></td>
                <td><input type="number" name="ReinvestingDays" value="@Model.ReinvestingDays" /></td>
                <td><input type="number" name="InitialPacks" value="@Model.InitialPacks" /></td>
                <td><input type="number" name="ReturnPerDayPerPack" value="@Model.ReturnPerDayPerPack" /></td>
                <td><input type="number" name="ExchangeRate" value="@Model.ExchangeRate" /></td>
            </tr>
            <tr>
                <td>Max active packs</td>
                <td>Active packs</td>
                <td>Total</td>
                <td>Initial investment</td>
                <td>Profit</td>
                <td>Peak return/Day</td>
                <td>Peak return/Month</td>
                <td>Profit percent</td>
            </tr>
            <tr>
                <td><input type="text" name="MaxActivePacks" value="@Model.MaxActivePacks" readonly /></td>
                <td><input type="text" name="ActivePacks" value="@Model.ActivePacks" readonly /></td>
                <td><input type="text" name="Total" class="blue" value="@Model.Total" readonly /></td>
                <td><input type="text" name="InitialInvestment" class="red" value="@Model.InitialInvestment" readonly /></td>
                <td><input type="text" name="Profit" class="lime" value="@Model.Profit" readonly /></td>
                <td><input type="text" name="PeakReturnPerDay" value="@Model.PeakReturnPerDay" readonly /></td>
                <td><input type="text" name="PeakReturnPerMonth" value="@Model.PeakReturnPerMonth" readonly /></td>
                <td><input type="text" name="ProfitPercent" value="@Model.ProfitPercent" readonly /></td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <td>Total (ROL)</td>
                <td>Init. invest. (ROL)</td>
                <td>Profit (ROL)</td>
                <td>Peak/Day (ROL)</td>
                <td>Peak/Month (ROL)</td>
                <td>Total percent</td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <td><input type="text" name="TotalROL" class="blue" value="@Model.TotalROL" readonly /></td>
                <td><input type="text" name="InitialInvestmentROL" class="red" value="@Model.InitialInvestmentROL" readonly /></td>
                <td><input type="text" name="ProfitROL" class="lime" value="@Model.ProfitROL" readonly /></td>
                <td><input type="text" name="PeakReturnPerDayROL" value="@Model.PeakReturnPerDayROL" readonly /></td>
                <td><input type="text" name="PeakReturnPerMonthROL" value="@Model.PeakReturnPerMonthROL" readonly /></td>
                <td><input type="text" name="TotalPercent" value="@Model.TotalPercent" readonly /></td>
            </tr>
            <tr>
                <td><button name="OptimalTotalDays" asp-controller="@controller" asp-action="OptimalTotalDays">Opt. total days</button></td>
                <td><button name="OptimalReinvestingDays" asp-controller="@controller" asp-action="OptimalReinvestingDays">Opt. reinv. days</button></td>
                <td><button name="OptimalInitialPacks" asp-controller="@controller" asp-action="OptimalInitialPacks">Opt. initial packs</button></td>
                <td><button name="Calculate" asp-controller="@controller" asp-action="Calculate">Calculate</button></td>
                <td><button name="ToROL" asp-controller="@controller" asp-action="ToROL">To ROL</button></td>
            </tr>
            <tr>
                <td>Timer 1 (ms)</td>
                <td>Timer 2 (ms)</td>
                <td>Timer 3 (ms)</td>
            </tr>
            <tr>
                <td><input type="text" name="Timer1" value="@Model.Timer1" readonly /></td>
                <td><input type="text" name="Timer2" value="@Model.Timer2" readonly /></td>
                <td><input type="text" name="Timer3" value="@Model.Timer3" readonly /></td>
            </tr>
        </table>
    </div>
</form>

AdPackSimMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdPackSimMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AdPackSimMvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GenericList" asp-action="Index">Safe code using a generic List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UnsafeStructArray" asp-action="Index">Unsafe code using a struct Array</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AdPackSimMvc
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AdPackSimMvc/Views/UnsafeStructArray/Index.cshtml
@model Data;

<h1>Unsafe code using a struct Array</h1>

<p>Calculate: Unsafe code using a struct Array.</p>

@{
    ViewData["Title"] = "Unsafe Struct Array";
    ViewBag.Controller = "UnsafeStructArray";
    await Html.RenderPartialAsync("Calculator", Model);
}